
;***************************************************************************
;
;   Copyright (c) 1997, 1998 Timpanogas Research Group, Inc.  All Rights
;                            Reserved.
;
;   This program is an unpublished work of TRG, Inc. and contains
;   trade secrets and other proprietary information.  Unauthorized
;   use, copying, disclosure, or distribution of this file without the
;   consent of TRG, Inc. can subject the offender to severe criminal
;   and/or civil penalities.
;
;
;   AUTHOR   :  Jeff V. Merkey
;   FILE     :  VERSION.INC
;   DESCRIP  :  Version specific defines for MANOS v1.0
;   DATE     :  March 19, 1998
;
;
;***************************************************************************

MAX_PROCESSORS     EQU    8
OPT_IA32_MANOS     EQU    1

IA32_OPCODE        EQU    1
MERCED_OPCODE      EQU    0
ALPHA_OPCODE       EQU    0

MAJOR_VERSION      EQU    1
MINOR_VERSION      EQU    0
BUILD_VERSION      EQU    3
