
;***************************************************************************
;
;   Copyright (c) 1997, 1998 Timpanogas Research Group, Inc.  All Rights
;                            Reserved.
;
;   AUTHOR   :  Jeff V. Merkey
;   FILE     :  VERSION.INC
;   DESCRIP  :  Version specific defines for MANOS v1.0
;   DATE     :  March 19, 1998
;
;
;***************************************************************************

MAX_PROCESSORS     EQU    8
OPT_IA32_MANOS     EQU    1

IA32_OPCODE        EQU    1
MERCED_OPCODE      EQU    0
ALPHA_OPCODE       EQU    0

MAJOR_VERSION      EQU    1
MINOR_VERSION      EQU    0
BUILD_VERSION      EQU    3
